spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/modelo_er_fase2?createDatabaseIfNotExist=true
    username : root
    password: Manchas12345.
server:
  port: 8282